from __future__ import annotations

import base64
import os
import re
from typing import Any
from urllib.parse import urlparse

import httpx
from fastapi import FastAPI, HTTPException
from pydantic import BaseModel, Field

app = FastAPI(title="AI Code Screening API", version="0.1.0")

GITHUB_API = "https://api.github.com"
SUPPORTED_EXTENSIONS = {
    ".kt", ".java", ".py", ".js", ".ts", ".tsx", ".jsx", ".go", ".rs",
    ".cpp", ".c", ".h", ".cs", ".swift", ".dart"
}
IGNORED_NAMES = {"build", ".gradle", "node_modules", "vendor", "dist"}


class AnalyzeRequest(BaseModel):
    repository_url: str = Field(..., min_length=1)


class Finding(BaseModel):
    file: str
    lines: str
    score: int
    reason: str


class AnalysisResponse(BaseModel):
    repository: str
    files_analyzed: int
    findings: list[Finding]
    questions: list[str]


def parse_repo(url: str) -> tuple[str, str]:
    parsed = urlparse(url.strip())
    if parsed.netloc.lower() not in {"github.com", "www.github.com"}:
        raise ValueError("Нужна ссылка на GitHub repository")
    parts = [p for p in parsed.path.split("/") if p]
    if len(parts) < 2:
        raise ValueError("Ссылка должна иметь вид https://github.com/owner/repository")
    return parts[0], parts[1].replace(".git", "")


def headers() -> dict[str, str]:
    result = {
        "Accept": "application/vnd.github+json",
        "X-GitHub-Api-Version": "2026-03-10",
        "User-Agent": "ai-code-screening-coursework",
    }
    token = os.getenv("GITHUB_TOKEN")
    if token:
        result["Authorization"] = f"Bearer {token}"
    return result


async def github_get(client: httpx.AsyncClient, path: str) -> Any:
    response = await client.get(f"{GITHUB_API}{path}", headers=headers())
    if response.status_code >= 400:
        raise HTTPException(status_code=response.status_code, detail=f"GitHub API: {response.text[:300]}")
    return response.json()


def is_source_file(path: str) -> bool:
    return any(path.lower().endswith(ext) for ext in SUPPORTED_EXTENSIONS) and not any(
        part in IGNORED_NAMES for part in path.split("/")
    )


def suspicious_signals(code: str) -> tuple[int, list[str]]:
    score = 0
    reasons: list[str] = []
    lines = code.splitlines()
    non_empty = [line for line in lines if line.strip()]

    if len(non_empty) > 10:
        avg_len = sum(len(line) for line in non_empty) / len(non_empty)
        if avg_len > 105:
            score += 18
            reasons.append("высокая средняя длина строк")

    if re.search(r"TODO|FIXME|PLACEHOLDER", code, re.IGNORECASE):
        score += 10
        reasons.append("шаблонные маркеры TODO/FIXME")

    if re.search(r"generated by|chatgpt|copilot|ai-generated", code, re.IGNORECASE):
        score += 40
        reasons.append("явные маркеры AI/generated в комментариях")

    generic_comments = len(re.findall(r"//\s*(this|that|the|function|method)\b", code, re.IGNORECASE))
    if generic_comments >= 3:
        score += 12
        reasons.append("много однотипных общих комментариев")

    if len(lines) > 20 and not re.search(r"(test|assert|expect|check)", code, re.IGNORECASE):
        score += 8
        reasons.append("нет очевидных признаков тестовой проверки")

    # Deliberately conservative: this is a screening signal, not proof of AI authorship.
    score = min(score, 95)
    if not reasons:
        reasons.append("выраженных эвристических признаков не найдено")
    return score, reasons


def make_questions(findings: list[Finding]) -> list[str]:
    questions: list[str] = []
    for finding in findings[:5]:
        questions.append(
            f"Объясните своими словами, как работает {finding.file} ({finding.lines}). "
            f"Почему выбран именно такой подход?"
        )
        questions.append(
            f"Какие альтернативы решению в {finding.file} вы рассматривали и какие у них компромиссы?"
        )
    if not questions:
        questions.append("Какой самый сложный участок проекта вы реализовали самостоятельно и почему?")
        questions.append("Как бы вы изменили архитектуру проекта при росте нагрузки в 10 раз?")
    return questions[:8]


@app.get("/health")
async def health() -> dict[str, str]:
    return {"status": "ok"}


@app.post("/api/analyze", response_model=AnalysisResponse)
async def analyze(request: AnalyzeRequest) -> AnalysisResponse:
    try:
        owner, repo = parse_repo(request.repository_url)
    except ValueError as exc:
        raise HTTPException(status_code=400, detail=str(exc)) from exc

    async with httpx.AsyncClient(timeout=20) as client:
        repo_data = await github_get(client, f"/repos/{owner}/{repo}")
        tree = await github_get(client, f"/repos/{owner}/{repo}/git/trees/{repo_data['default_branch']}?recursive=1")

        findings: list[Finding] = []
        files_analyzed = 0
        for item in tree.get("tree", []):
            path = item.get("path", "")
            if item.get("type") != "blob" or not is_source_file(path):
                continue
            if files_analyzed >= 30:
                break
            files_analyzed += 1
            blob = await github_get(client, f"/repos/{owner}/{repo}/git/blobs/{item['sha']}")
            try:
                code = base64.b64decode(blob.get("content", "")).decode("utf-8", errors="ignore")
            except Exception:
                continue

            score, reasons = suspicious_signals(code)
            if score >= 25:
                line_count = len(code.splitlines())
                end = min(line_count, 40)
                findings.append(
                    Finding(
                        file=path,
                        lines=f"1–{end}",
                        score=score,
                        reason="; ".join(reasons),
                    )
                )

    findings.sort(key=lambda x: x.score, reverse=True)
    questions = make_questions(findings)
    full_name = repo_data.get("full_name", f"{owner}/{repo}")
    return AnalysisResponse(
        repository=full_name,
        files_analyzed=files_analyzed,
        findings=findings,
        questions=questions,
    )
